packages:
  - '.'

patchedDependencies:
  '@capacitor/local-notifications@8.3.1': patches/@capacitor__local-notifications@8.3.1.patch
  'wouter@3.7.1': patches/wouter@3.7.1.patch
overrides:
  'tailwindcss>nanoid': 3.3.7
